export { default as PausePanelButtons } from "./components/PausePanelButtons.vue"
export { default as PausePanelSimpleText } from "./components/PausePanelSimpleText.vue"
export { default as PauseReplayHost } from "./components/PauseReplayHost.vue"
export { default as PauseVehicleConfigurationCombined } from "./components/PauseVehicleConfigurationCombined.vue"

import { getUiAppComponent } from "@/modules/apps/runtime"
export const Tasklist = getUiAppComponent("tasklist")

export { default as PauseNearbyActivitiesTab } from "./views/content/PauseNearbyActivitiesTab.vue"
export { default as PauseNearbyVehicles } from "./views/content/PauseNearbyVehicles.vue"
export { default as PauseMissionObjectives } from "./views/content/PauseMissionObjectives.vue"
export { default as PauseCareerProfileOverview } from "./views/content/PauseCareerProfileOverview.vue"
export { default as ProgressDigest } from "./views/content/ProgressDigest.vue"
export { default as ApmSuggestedMissions } from "./views/content/ApmSuggestedMissions.vue"
export { default as ProgressDomainInfo } from "./views/content/ProgressDomainInfo.vue"
export { default as ProgressMissionInfo } from "./views/content/ProgressMissionInfo.vue"
export { default as MilestoneDigest } from "./views/content/MilestoneDigest.vue"
export { default as CareerHistoryDigest } from "./views/content/CareerHistoryDigest.vue"

export { default as PauseVehicleTab } from "./views/content/PauseVehicleTab.vue"
export { default as PauseVehicleSpawned } from "./views/content/PauseVehicleSpawned.vue"
export { default as PauseVehicleSpawnedSelected } from "./views/content/PauseVehicleSpawnedSelected.vue"
export { default as PauseVehicleSpawnedSummary } from "./views/content/PauseVehicleSpawnedSummary.vue"
export { default as PauseVehiclePacks } from "./views/content/PauseVehiclePacks.vue"
export { default as PauseVehicleParts } from "./views/content/PauseVehicleParts.vue"
export { default as PauseVehicleTuning } from "./views/content/PauseVehicleTuning.vue"
export { default as PauseVehicleDebug } from "@/modules/pause/views/content/PauseVehicleDebug.vue"
export { default as PauseVehicleSkin } from "./views/content/PauseVehicleSkin.vue"
export { default as PauseVehicleSave } from "./views/content/PauseVehicleSave.vue"
export { default as PauseVehicleConfigListManage } from "@/modules/vehicleConfig/components/ConfigListManage.vue"

export { default as PauseEnvironmentWeather } from "./views/content/PauseEnvironmentWeather.vue"
export { default as PauseEnvironmentSimulation } from "./views/content/PauseEnvironmentSimulation.vue"
export { default as PauseEnvironmentTraffic } from "./views/content/PauseEnvironmentTraffic.vue"
export { default as PauseEnvironmentDigest } from "./views/content/PauseEnvironmentDigest.vue"

export { default as PauseMultiplayerTab } from "./views/content/PauseMultiplayerTab.vue"
export { default as PauseMultiplayerPlayerList } from "@/modules/multiplayer/components/PauseMultiplayerPlayerList.vue"
export { default as PauseMultiplayerSessionTab } from "@/modules/multiplayer/components/PauseMultiplayerSessionTab.vue"
export { default as PauseMultiplayerGamemodesTab } from "@/modules/multiplayer/components/PauseMultiplayerGamemodesTab.vue"
