// Credits data

export default
[
    { groupTitle: 'ui.credits.programmers', members: [
        {first: 'Thomas',        last: 'Fischer',          aka: 'tdev',          role: 'CEO'},
        {first: 'Lefteris',      last: 'Stamatogiannakis', aka: 'estama',        role: 'CTO / Physics / Sound / AI'},
        {first: 'Luis',          last: 'Anton Rebollo',    aka: 'Souga',         role: 'Lead Render Developer'},
        {first: 'Alex',          last: 'Spodheim',         aka: 'CrankyCleric',  role: 'Developer'},
        {first: 'Ananda Neelam', last: 'Thathayya',        aka: 'Nadeox1',       role: 'Technical Artist'},
        {first: 'Andrew',        last: 'Kabakwu',          aka: '',              role: 'Developer'},
        {first: 'Bruno',         last: 'Gonzalez Campo',   aka: 'stenyak',       role: 'Lead Game Engine Developer'},
        {first: 'Cosmin',        last: 'Traian',           aka: '',              role: 'Developer'},
        {first: 'Felix',         last: 'Unger',            aka: '',              role: 'Developer'},
        {first: 'George',        last: 'Troulitakis',      aka: 'AtmanB',        role: 'Developer'},
        {first: 'Guillem',       last: 'Ortega',           aka: '',              role: 'Developer'},
        {first: 'Kolya',         last: 'Garbalau',         aka: '',              role: 'Developer'},
        {first: 'Logane',        last: 'Ramez',            aka: 'Gadoy',         role: 'Developer'},
        {first: 'Lorenzo',       last: 'Bartali',          aka: '',              role: 'AI Developer'},
        {first: 'Ludger',        last: 'Meyer-Wülfing',    aka: 'meywue',        role: 'Developer'},
        {first: 'Luis',          last: 'Placid',           aka: '',              role: 'Developer'},
        {first: 'Nicusor',       last: 'Nedelcu',          aka: '',              role: 'Tools Developer'},
        {first: 'Oskar',         last: 'Vu',               aka: '',              role: 'Developer'},
        {first: 'Panos',         last: 'Karabelas',        aka: '',              role: 'Developer'},
        {first: 'Patrick ',      last: 'Schrangl',         aka: '',              role: 'Simulation Software Engineer'},
        {first: 'Petros',        last: 'Kondylis',         aka: '',              role: 'AI Developer'},
        {first: 'Ronny',         last: 'Nowak',            aka: '',              role: 'Developer'},
        {first: 'Thomas',        last: 'Portassau',        aka: 'thomatoes50',   role: 'Developer'},
        {first: 'Thomas',        last: 'Wilczynski',       aka: 'Gamergull',     role: 'Developer'},
        {first: 'Timo',          last: 'Stabbert',         aka: '',              role: 'Gameplay Dev Lead'},
        {first: 'Daniel',        last: 'Wakefield',        aka: '',              role: 'Developer'},
    ]},
    { groupTitle: 'ui.credits.vehiclePhysics', members: [
        {first: 'Fabian',        last: 'Enkler',           aka: 'Diamondback',   role: 'Vehicle Systems Lead'},
        {first: 'Angelo',        last: 'Matteo',           aka: 'angelo234',     role: 'Tools Developer'},
        {first: 'Aubrey',        last: 'Percival',         aka: '',              role: 'Vehicle Physics Engineer'},
        {first: 'Bobby',         last: 'Villeneuve',       aka: 'Binkey',        role: 'Vehicle Physics Engineer'},
        {first: 'Corey',         last: 'Bergerud',         aka: 'Goosah',        role: 'Vehicle Physics Engineer'},
        {first: 'Efe Can',       last: 'Kiraz',            aka: 'RenAzuma66',    role: 'Vehicle Physics Engineer'},
        {first: 'Grzegorz',      last: 'Węgrzyn',          aka: 'AiTorror',      role: 'Vehicle Physics Engineer / QA'},
        {first: 'Jack',          last: 'Jermany',          aka: '',              role: 'Vehicle Physics Engineer / QA'},
        {first: 'Oliver',        last: 'Čajka',            aka: 'MRcrash',       role: 'Vehicle Physics Engineer'},
        {first: 'Piotr',         last: 'Gajek',            aka: 'Agent_Y',       role: 'Vehicle Physics Engineer / QA'},
        {first: 'Toma Ioan',     last: ' Turcu',           aka: '',              role: 'Vehicle Physics Engineer'},
    ]},
    { groupTitle: 'ui.credits.vehicleArt', members: [
        {first: 'Gabriel',       last: 'Fink',       aka: 'gabester',   role: 'Vehicle Art Director'},
        {first: 'Jared',         last: 'Samuelson',  aka: '',           role: 'Vehicle Team Lead / Subaru Expert'},
        {first: 'Alexandr',      last: 'Shesternin', aka: '',           role: '3D Vehicle Artist'},
        {first: 'Andreas',       last: 'Focht',      aka: '',           role: 'Vehicle Concept Artist'},
        {first: 'Daniel',        last: 'Russo',      aka: 'A3DR',       role: '3D Vehicle Artist'},
        {first: 'Dennis',        last: 'Mateja',     aka: 'NinetyNine', role: 'Vehicle Designer'},
        {first: 'Manish',        last: 'Rawat',      aka: '',           role: '3D Vehicle Artist'},
    ]},
    { groupTitle: 'ui.credits.environmentArtists', members: [
        {first: 'Sam',         last: 'Hutchinson',     aka: 'LJFHutch',    role: 'Environment Art Director'},
        {first: 'Luca',        last: 'Brighi',         aka: '',            role: 'Lead 3D Environment Artist'},
        {first: 'Huiqin',      last: 'Li',             aka: '',            role: '3D Environment Artist'},
        {first: 'Sebastien',   last: 'Pelletier',      aka: 'DoullPepper', role: '3D Environment Artist'},
    ]},
    { groupTitle: 'ui.credits.conceptArtists', members: [
        {first: 'Mary Jane',   last: 'Pajaron',         aka: '', role: '2D Concept Artist'},
    ]},
    { groupTitle: 'ui.credits.gameDesigners', members: [
        {first: 'James',               last: 'Heslop',     aka: 'Krallopian',    role: 'Game Design Lead'},
        {first: 'Alex',                last: 'Bird',       aka: '',              role: 'Gameplay Developer'},
        {first: 'Rob',                 last: 'Herridge',   aka: 'HighDef',       role: 'Gameplay Developer / QA'},
    ]},
    { groupTitle: 'ui.credits.ui', members: [
        {first: 'Pavel',          last: 'Tiunov',           aka: 'Dizboosta',     role: 'UI Lead'},
        {first: 'Destiny',        last: 'Abellana',         aka: '',              role: 'Developer'},
        {first: 'Konstantin',     last: 'Kitmanov',         aka: '',              role: 'Developer'},
        {first: 'Stani',          last: 'Tolmacheva',       aka: 'Snowly',        role: 'Developer'},
    ]},
    { groupTitle: 'ui.credits.sound', members: [
        {first: 'Mark',           last: 'Knight',    aka: 'TDK', role: 'Audio Designer'},
        {first: 'Sebastian',      last: 'Emling',    aka: '',    role: 'Audio Designer'},
    ]},
    { groupTitle: 'ui.credits.qa', members: [
        {first: 'Colin',          last: 'Wenz',         aka: 'synsol',     role: 'QA Lead'},
        {first: 'Przemysław',     last: 'Wolny',        aka: 'Car_Killer', role: 'QA / Mod Support'},
        {first: 'Grzegorz',       last: 'Węgrzyn',      aka: 'AiTorror',   role: 'Vehicle Physics Engineer / QA'},
        {first: 'Jack',           last: 'Jermany',      aka: '',           role: 'Vehicle Physics Engineer / QA'},
        {first: 'Piotr',          last: 'Gajek',        aka: 'Agent_Y',    role: 'Vehicle Physics Engineer / QA'},
        {first: 'Rob',            last: 'Herridge',     aka: 'HighDef',    role: 'Gameplay Developer / QA'},
        {first: 'Scott',          last: 'Yeates',       aka: '',           role: 'QA / Mod Support'},
    ]},
    { groupTitle: 'ui.credits.production', members: [
        {first: 'Ryan',           last: 'Dunne',               aka: '',      role: 'Producer'},
    ]},
    { groupTitle: 'ui.credits.comms', members: [
        {first: 'Nataliia',     last: 'Dmytriievska',    aka: 'Leeloo',         role: 'Communications & Marketing Lead'},
        {first: 'Bernice',      last: 'Mills',           aka: 'Bee',            role: 'Community Support & Marketing Specialist'},
        {first: 'Mariia',       last: 'Gumarova',        aka: 'Fluffy Panda',   role: 'Customer Support & Marketing Specialist'},
        {first: 'Vincent',      last: 'Liu',             aka: '',               role: 'Community & Marketing Specialist (APAC)'},
    ]},
    { groupTitle: 'ui.credits.research', members: [
        {first: 'Chrysanthi',       last: 'Papamichail',    aka: '',          role: 'Lead Research Software Engineer'},
        {first: 'Abdulrahman',      last: 'Saeed',          aka: '',          role: 'Research Software Engineer'},
        {first: 'Adam',             last: 'Ivora',          aka: '',          role: 'Research Software Engineer'},
        {first: 'Aubin',            last: 'Sionville',      aka: '',          role: 'Research Software Engineer Intern'},
        {first: 'David',            last: 'Stark',          aka: '',          role: 'Research Software Engineer'},
        {first: 'Florian',          last: 'Faistauer',      aka: '',          role: 'Vehicle Simulation Expert'},
        {first: 'Sayali',           last: 'Rajhans',        aka: '',          role: 'Research Software Engineer'},
        {first: 'Iskren',           last: 'Rusimov',        aka: '',          role: 'Research Software Engineer Intern'},
    ]},
    { groupTitle: 'ui.credits.organization', members: [
        {first: 'Christoforos',   last: 'Lambrianidis',     aka: '',          role: 'CFO'},
        {first: 'Joseph',         last: 'Inba Raj',         aka: '',          role: 'HR & Talent Acquisition Lead'},
        {first: 'Cecilia',        last: 'Sari',             aka: '',          role: 'Recruitment Specialist'},
        {first: 'Dimitra',        last: 'Litsardou',        aka: 'Thamy',     role: 'EU / Co-funding Advisory Specialist'},
        {first: 'Eva',            last: 'Pigova',           aka: '',          role: 'Senior Program Manager'},
        {},
        {first: 'Maria',          last: 'Kosmachevskaya',   aka: '',          role: 'Business Development Intern'},
        {first: 'Özge',           last: 'Altinkaya Erkok',  aka: '',          role: 'Communication Consultant'},
        {first: 'Sabrina',        last: 'Wee',              aka: '',          role: 'Business Development Manager'},
        {},
        {first: 'Sandra',         last: 'Campos',           aka: '',          role: 'Accounting Assistant'},
        {first: 'Ulrike',         last: 'Lentz',            aka: '',          role: 'Executive Assistant'},
    ]},
    { groupTitle: 'ui.credits.sysops', members: [
        {first: 'Charalampos',    last: 'Tsipizidis',    aka: '', role: 'System Administrator'},
        {first: 'Dimitrios',      last: 'Folias',        aka: '', role: 'System Administrator'},
    ]},
    { groupTitle: 'ui.credits.additionalVehiclePhysics', members: [
        {first: 'Will',           last: 'Leader',           aka: '',          role: 'Off-road Suspension Development & Vehicle Dynamics'},
    ]},
    { groupTitle: 'ui.credits.additionalVehicleArt', members: [
        {first: 'Ashish',         last: 'Singh',            aka: '',          role: 'Freelance 3D Vehicle Artist'},
        {first: 'Juan Manuel',    last: 'Orcellet',         aka: '',          role: 'Freelance 3D Vehicle Artist'},
        {first: 'M. Yusuf',       last: 'Bolukbasi',        aka: '',          role: 'Freelance Vehicle Artist'},
        {first: 'Naman',          last: 'Deep',             aka: '',          role: 'Freelance 3D Vehicle Artist'},
    ]},
    { groupTitle: 'ui.credits.externalContributors', members: [
        {first: 'Da',             last: 'Li',               aka: '',          role: 'Lua Development Contributor'},
        {first: 'Ruhmit',         last: 'Sahu ',            aka: '',          role: 'Lua Development Contributor'},
        {first: 'Jethro',         last: 'Dunn',             aka: '',          role: 'Audio Outsourcer'},
        {first: 'Max',            last: 'Schumann',         aka: '',          role: 'Audio Outsourcer'},
    ]},
    { groupTitle: 'ui.credits.localization', groupSubtitle: 'Lionbridge Technologies, LLC', groupTertiaryTitle: 'ui.credits.localizationTertiary', members: [
        {first: 'Baptistin le Blanc',      last: '',    aka: '',    role: 'Content Delivery Director'},
        {first: 'Marcos López',            last: '',    aka: '',    role: 'Site Manager'},
        {first: 'Inês Lisboa',             last: '',    aka: '',    role: 'PM Team Lead'},
        {first: 'Gabriel Fernandes',       last: '',    aka: '',    role: 'Localization PM'},
        {first: 'Daniela Rigon',           last: '',    aka: '',    role: 'Localization PM'},
        {first: 'Lydia Campomanes Miguel', last: '',    aka: '',    role: 'Localization PM'},
        { divider: true },
        {first: 'Cesar S. Paulicchi',      last: '',    aka: '',    role: 'Brazilian Portuguese Language Coordinator'},
        {first: 'Evelyn Trippo',           last: '',    aka: '',    role: 'Brazilian Portuguese Language Coordinator'},
        {first: 'Victor Gama',             last: '',    aka: '',    role: 'Brazilian Portuguese Language Coordinator'},
        { slideBreak: true },
        {first: 'Sangjin Lee',             last: '',    aka: '',    role: 'Korean Translator'},
        {first: 'Kosuke Takeda',           last: '',    aka: '',    role: 'Japanese Translator'},
        {first: 'Krzysztof Dudek',         last: '',    aka: '',    role: 'Polish Translator'},
        {first: 'Olivier Ragheboom',       last: '',    aka: '',    role: 'French Translator'},
        {first: 'Pablo Burgos González',   last: '',    aka: '',    role: 'Spanish (Spain) Translator'},
        {first: 'Ana Carolina Calabria',   last: '',    aka: '',    role: 'Portuguese (Brazil) Translator'},
        {first: 'Cristina Villar',         last: '',    aka: '',    role: 'Portuguese (Brazil) Translator'},
        {first: 'Leonardo Rivabem',        last: '',    aka: '',    role: 'Portuguese (Brazil) Translator'},
        {first: 'Raphael Boccardo',        last: '',    aka: '',    role: 'Portuguese (Brazil) Translator'},
        {first: 'Andrei Kostrikov',        last: '',    aka: '',    role: 'Russian Translator'},
        {first: 'Eladio Gonzalez',         last: '',    aka: '',    role: 'Spanish (Latin America) Translator'},
        {first: 'Alex Huang',              last: '',    aka: '',    role: 'Chinese (Simplified) Translator'},
        {first: 'Rui Valente',             last: '',    aka: '',    role: 'Portuguese (Portugal) Translator'},
        {first: 'Konstantinos Fotopoulos', last: '',    aka: '',    role: 'German Translator'},
        {first: 'Bernhard Trecksel',       last: '',    aka: '',    role: 'German Translator'},
        { slideBreak: true },
        {first: 'Jaewook Lee',             last: '',    aka: '',    role: 'Korean Reviewer'},
        {first: 'Rutsuko Moji',            last: '',    aka: '',    role: 'Japanese Reviewer'},
        {first: 'Sara Jiménez García',     last: '',    aka: '',    role: 'Spanish (Spain) Reviewer'},
        {first: 'Bruna Aguiar',            last: '',    aka: '',    role: 'Portuguese (Brazil) Reviewer'},
        {first: 'Camila Ascêncio',         last: '',    aka: '',    role: 'Portuguese (Brazil) Reviewer'},
        {first: 'Guilherme Godoy Guerreiro',last: '',   aka: '',    role: 'Portuguese (Brazil) Reviewer'},
        {first: 'Germain Baridon',         last: '',    aka: '',    role: 'French Reviewer'},
        {first: 'Dobromira Lenczowska',    last: '',    aka: '',    role: 'Polish Reviewer'},
        {first: 'Alex Dramashko',          last: '',    aka: '',    role: 'Russian Reviewer'},
        {first: 'Hugo Miguel Martins Lobo',last: '',    aka: '',    role: 'Portuguese (Portugal) Reviewer'},
        {first: 'Dominik Langer',          last: '',    aka: '',    role: 'German Reviewer'},
        {first: 'Martin Böcking',          last: '',    aka: '',    role: 'German Reviewer'},
    ]},
    { groupTitle: 'ui.credits.localization', groupSubtitle: 'Alconost Inc.', groupTertiaryTitle: 'ui.credits.localizationTertiary', members: [
        {first: 'Dima Vinitski',                           last: '',    aka: '',    role: 'Head of Vendor'},
        {first: 'Antanina Zaleschenok',                    last: '',    aka: '',    role: 'Vendor Manager'},
        { divider: true },
        {first: 'Dmitry Iuko',                             last: '',    aka: '',    role: 'Business Development Manager'},
        {first: 'Diana Yaromskaya',                        last: '',    aka: '',    role: 'Localization Project Manager'},
        {first: 'Olga Matselya',                           last: '',    aka: '',    role: 'Localization Project Manager'},
        { slideBreak: true },
        {first: 'Adam Siemienski',                         last: '',    aka: '',    role: 'Localization Specialist (Polish)'},
        {first: 'Christian Geick',                         last: '',    aka: '',    role: 'Localization Specialist (German)'},
        {first: 'Damien Leboulanger',                      last: '',    aka: '',    role: 'Localization Specialist (French)'},
        {first: 'Daniel Catarino',                         last: '',    aka: '',    role: 'Localization Specialist (Portuguese)'},
        {first: 'David Kim',                               last: '',    aka: '',    role: 'Localization Specialist (Korean)'},
        {first: 'Georgii Kopylov',                         last: '',    aka: '',    role: 'Localization Specialist (Russian)'},
        {first: 'Helder Lima Santos da Rocha',             last: '',    aka: '',    role: 'Localization Specialist (Brazilian Portuguese)'},
        {first: 'Korbin Yeh',                              last: '',    aka: '',    role: 'Localization Specialist (Chinese)'},
        {first: 'Liang Zhang',                             last: '',    aka: '',    role: 'Localization Specialist (Chinese)'},
        {first: 'Martín Enrique Santos Damiano Alcorta',   last: '',    aka: '',    role: 'Localization Specialist (LATAM Spanish)'},
        {first: 'Nuno Miranda',                            last: '',    aka: '',    role: 'Localization Specialist (Portuguese)'},
        {first: 'Ruben Pedro Lopez Sanchez',               last: '',    aka: '',    role: 'Localization Specialist (Spanish)'},
        {first: 'Tatiana Vasilieva Kalashnikova',          last: '',    aka: '',    role: 'Localization Specialist (Spanish)'},
        {first: 'Zhao Jin',                                last: '',    aka: '',    role: 'Localization Specialist (Japanese)'},
    ]},
    { groupTitle: 'ui.credits.formerEmployee', members: [
        {first: 'Aaron',         last: 'Sutcliffe',         aka: '',        role: 'Developer / Vehicle Creation'},
        {first: 'Alex',          last: 'Raskin',            aka: '',        role: 'DevOps Engineer'},
        {first: 'Artem',         last: 'Arbatskii',         aka: '',        role: 'Developer'},
        {first: 'Arturo',        last: 'Campos',            aka: '',        role: 'Developer'},
        {first: 'Ben',           last: 'Payne',             aka: '',        role: 'Developer'},
        {first: 'Boluwatife',    last: 'Falaye',            aka: '',        role: 'Developer'},
        {first: 'Clément',       last: 'Roche',             aka: '',        role: 'Developer'},
        {first: 'Edelmar',       last: 'Schneider',         aka: '',        role: 'Developer'},
        {first: 'Eike',          last: 'Externest',         aka: '',        role: 'Developer'},
        {first: 'Emre',          last: 'Kut',               aka: '',        role: 'Developer'},
        {first: 'Jali',          last: 'Hautala',           aka: 'Jalkku',  role: 'Developer'},
        {first: 'Jeremy',        last: 'Lu',                aka: '',        role: 'Developer'},
        {first: 'John',          last: 'Beinecke',          aka: '',        role: 'Developer'},
        {first: 'Juan',          last: 'Mendez',            aka: '',        role: 'Developer'},
        {first: 'Leander',       last: 'Beernaert',         aka: '',        role: 'Game Engine Developer'},
        {first: 'Marc',          last: 'Müller',            aka: '',        role: 'Developer'},
        {first: 'Mark',          last: 'Vince',             aka: '',        role: 'Developer'},
        {first: 'Matti',         last: 'Yrjänheikki',       aka: 'Masa',    role: 'Developer'},
        {first: 'Max',           last: 'Razer',             aka: '',        role: 'Developer'},
        {first: 'Mayowa David',  last: 'Abogunrin',         aka: '',        role: 'Developer'},
        {first: 'Moncef',        last: 'Slimane',           aka: '',        role: 'Developer'},
        {first: 'Nourelhoda',    last: 'Mohamed',           aka: '',        role: 'Developer'},
        {first: 'Pascale',       last: 'Maul',              aka: '',        role: 'Developer'},
        {first: 'Paul',          last: 'De Almeida',        aka: '',        role: 'AI Developer'},
        {first: 'Paul',          last: 'Görs',              aka: '',        role: 'Developer'},
        {first: 'Peter',         last: 'Landwehr',          aka: '',        role: 'Developer'},
        {first: 'Petteri',       last: 'Koivumäki',         aka: '',        role: 'Developer'},
        {first: 'Valery',        last: 'Dolotin',           aka: '',        role: 'AI Developer'},
        {first: 'Vasilis',       last: 'Douvaras',          aka: '',        role: 'Developer'},
        {first: 'Vatroslav ',    last: 'Bodrozic',          aka: '',        role: 'Developer'},
        {first: 'Waldemar',      last: 'Zeitler',           aka: '',        role: 'Developer'},
        {first: 'Xiaoyi',        last: 'Wang',              aka: '',        role: 'Developer'},
        {},
        {first: 'Adrian',        last: 'Baboi',             aka: '',        role: 'Vehicle Creation'},
        {first: 'Brian',         last: 'Rickets',           aka: '',        role: 'Vehicle Systems Engineer'},
        {first: 'Brandon',       last: 'Proulx',            aka: 'Hondune', role: 'Vehicle Creation'},
        {first: 'Carlos',        last: 'Bergillos Varela',  aka: 'CarlosAir',role:'Content Creation'},
        {first: 'David',         last: 'Thurlbeck',         aka: '',        role: 'Vehicle Creation'},
        {first: 'Davide',        last: 'Serpi',             aka: '',        role: 'Vehicle Dynamics Control Intern'},
        {first: 'Janne',         last: 'Nummela',           aka: '',        role: 'Vehicle Creation'},
        {first: 'Jukka',         last: 'Muikkula',          aka: 'Miura',   role: 'Vehicle Creation'},
        {first: 'Karol',         last: 'Miklas',            aka: '',        role: 'Freelance 3D Vehicle Artist'},
        {first: 'Mardem',        last: 'Pires das Dores',   aka: '',        role: 'Vehicle Creation'},
        {first: 'Mikko',         last: 'Lesonen',           aka: '',        role: 'Vehicle Creation'},
        {first: 'Renju',         last: 'Therakathu',        aka: '',        role: 'Vehicle Creation'},
        {first: 'Sam',           last: 'Millington',        aka: 'DrowsySam',role:'Vehicle Creation / Support'},
        {first: 'Sebastian',     last: 'Wessel',            aka: '',        role: 'Vehicle Creation'},
        {first: 'Virtual Mechanix',last: '',                aka: '',        role: 'Vehicle Creation - Outsourcing Agency'},
        {first: 'Winston',       last: 'Broderick',         aka: '',        role: 'Vehicle Creation'},
        {first: 'Quinn',         last: 'Howling',           aka: 'SpeedHero',role: 'Vehicle Physics Designer'},
        {first: 'Mitchell',      last: 'Sahl',              aka: 'B25Mitch',role: '3D Vehicle / Environment Artist'},
        {},
        {first: 'Christin',      last: 'Walther',           aka: '',        role: 'Lead 3D Artist'},
        {first: 'Justin',        last: 'Roczniak',          aka: 'Donoteat',role: 'Environment Artist'},
        {first: 'Lisa',          last: 'Steinberg',         aka: '',        role: '2D Artist'},
        {first: 'Moses',         last: 'Mulinge',           aka: '',        role: '2D Artist'},
        {},
        {first: 'Barend',        last: 'van der Meulen',    aka: '',        role: 'Content Creator'},
        {first: 'Matthias',      last: 'Niebergall',        aka: '',        role: 'Game Designer'},
        {first: 'SanityCheckMyGame',   last: '',            aka: '',        role: 'Additional Design'},
        {},
        {first: 'Gabriel Puretas',last: 'Moral',            aka: '',        role: 'UX Intern'},
        {first: 'Georgios',      last: 'Siantikos',         aka: 'gntikos', role: 'User Interface'},
        {first: 'Jonathan',      last: 'Randy',             aka: '',        role: 'Lead Developer'},
        {first: 'Mirco',         last: 'Weigel',            aka: 'theshark',role: 'User Interface'},
        {first: 'Svetlozar',     last: 'Valchev',           aka: '',        role: 'User Interface'},
        {first: 'Theodoros',     last: 'Manouilidis',       aka: '',        role: 'User Interface'},
        {first: 'Yale',          last: 'Hartmann',          aka: '',        role: 'User Interface'},
        {},
        {first: 'Arend',         last: 'Stührmann',         aka: '',        role: 'Producer'},
        {first: 'Marie Cécile',  last: 'Jacq',              aka: '',        role: 'Producer'},
        {first: 'Nhung Van',     last: 'Ho',                aka: '',        role: 'Project Management'},
        {},
        {first: 'Bhavinkumar Babulal',last: 'Arya',         aka: '',        role: 'Research Software Engineer'},
        {first: 'Carol',         last: 'Halim',             aka: 'Carotte', role: 'Research Software Engineer'},
        {first: 'Elmar',         last: 'Berghöfer',         aka: '',        role: 'Research'},
        {first: 'Mattia',        last: 'Vicari',            aka: '',        role: 'Research Software Engineer'},
        {},
        {first: 'Camila',        last: 'Navia',             aka: '',        role: 'Operations Assistant'},
        {first: 'Danish',        last: 'Abbasi',            aka: '',        role: 'Business Development Intern'},
        {first: 'Lucien',        last: 'Frei',              aka: '',        role: 'Business Development Intern'},
        {first: 'Renars',        last: 'Skesteris',         aka: '',        role: 'Business Development Intern'},
        {first: 'Weiwei',        last: 'Kong',              aka: '',        role: 'Business Development Intern'},
        {first: 'Özgen',         last: 'Saatçilar',         aka: '',        role: 'Communications Consultant'},
        {first: 'Saskia',        last: 'Opitz',             aka: '',        role: 'Administration'},
        {},
        {first: 'Hala',          last: 'Mahmoud',           aka: '',        role: 'Quality Assurance'},
        {first: 'Jan Niklas',    last: 'Hasse',             aka: '',        role: 'Quality Assurance'},
        {first: 'Kamil',         last: 'Kozak',             aka: '',        role: 'Quality Assurance'},
        {first: 'Kemisola',      last: 'Adeniyi',           aka: '',        role: 'Quality Assurance'},
        {first: 'Kaja',          last: 'Jambrek',           aka: '',        role: 'Quality Assurance'},
        {first: 'Rajinder',      last: 'Rajinder',          aka: '',        role: 'Quality Assurance'},
        {first: 'Safdar',        last: 'Mahmood',           aka: '',        role: 'Quality Assurance'},
        {first: 'Uros',          last: 'Sakic',             aka: 'Uki',     role: 'QA / Mod Support / Tools QA'},
        {},
        {first: 'Konstantinos',  last: 'Stamou',            aka: '',        role: 'System Administrator'},
        {},
        {first: 'Erik',          last: 'Heldt',             aka: '',        role: 'Documentation'},
        {first: 'Maxime',        last: 'Desharnais',        aka: '',        role: 'Documentation'},
        {first: 'Harm',          last: 'Schulz',            aka: '',        role: 'Student Assistant'},
        {first: 'Annisa',        last: 'Utami',             aka: '',        role: 'Student Assistant'},
        {first: 'Brandon',       last: 'Lynch',             aka: 'Chuck_Norris_',  role: 'Community Coordinator'},
        {first: 'Monica',        last: 'Huang',             aka: '',        role: 'Community Coordinator'},
        {first: 'Slawomir',      last: 'Niemczyk',          aka: 'Sedricoo',role: 'Community Coordinator'},
    ]},
    { groupTitle: 'ui.credits.ourAwesomeCommunity', members: [
        {first: 'Daniel',   last: 'Jones',       aka: 'daniel_j'},
        {first: 'Dennis',   last: 'Wrekenhorst', aka: 'Dennis-W'},
        {first: 'Dustin',   last: 'Kutchara',    aka: 'dkutch'},
        {first: 'Kristian', last: 'Fagerland',   aka: ''},
        {first: 'Richard',  last: 'Sixsmith',    aka: 'Metalmuncher'},
        {first: 'Sergy',    last: 'Karpowicz',   aka: '0xsergy'},
        {first: 'Sven',     last: 'Nabeck',      aka: 'sputnik_1'},
        {first: 'Tom',      last: 'Verhoeve',    aka: 'Mythbuster'},
        {first: 'Yannis',   last: 'Vaiopoulos',  aka: 'JohnV'},
        {first: '',         last: '',            aka: 'Fufsgfen'}
    ]},
    { groupTitle: 'ui.credits.specialThanksTo', members: [
        {first: 'Pierre-Michel',   last: 'Ricordel',     aka: 'pricorde'},
    ]},
    { groupTitle: 'ui.credits.soundtrack', members: [
        {first: 'Gabriel "gabester" Fink',    last: 'Copyright 2014', aka: 'Credits: Lonle'},
        {first: 'Mark "TDK" Knight',          last: 'Copyright 2018', aka: 'Front End'},
        {first: 'Mark "TDK" Knight',          last: 'Copyright 2018', aka: 'Lightrunner: Element No. 10'},
        {first: 'Mark "TDK" Knight',          last: 'Copyright 2018', aka: 'Lightrunner: Getting Away'},
        {first: 'Mark "TDK" Knight',          last: 'Copyright 2018', aka: 'Lightrunner: Juno Rocks'},
        {first: 'Mark "TDK" Knight',          last: 'Copyright 2018', aka: 'Lightrunner: Neon Night Racer'},
        {first: 'Mark "TDK" Knight',          last: 'Copyright 2018', aka: 'Lightrunner: Night Driver'}
    ]},
    { groupTitle: 'ui.credits.madePossibleWith', members: [
        {first: 'FMOD Studio by Firelight Technologies Pty Ltd.', last: '',                aka: ''},
        {first: 'LuaJIT',                                         last: '',                aka: ''},
        {first: 'lua-intf, LuaBridge',                            last: '',                aka: ''},
        {first: 'Chromium Embedded Framework',                    last: '',                aka: ''},
        {first: 'AngularJS',                                      last: '',                aka: ''},
        {first: 'Vue.js',                                         last: '',                aka: ''},
        {first: 'Material Design',                                last: '',                aka: ''},
        {first: 'LuaSocket',                                      last: '',                aka: ''},
        {first: 'Dear ImGui',                                     last: '',                aka: ''},
        {first: 'Blender ®',                                      last: 'www.blender.org', aka: ''},
    ]},
    { groupTitle: '', members: [
        {first: '“DUALSHOCK” and “DualSense” are registered trademarks or trademarks of Sony Interactive Entertainment Inc. Library programs for DUALSHOCK®4 and DualSense™ wireless controllers © 2022 Sony Interactive Entertainment Inc.', last: '',                aka: ''},
    ]}
]
