// in-memory equivalent of the auto-export vite plugins that normally output to /generated/*

import { SRC_PATH, GENERATED_PATH, RT_DEV } from "../config.js"
import { immediateFiles, filesUnder } from "../host/files.js"

const banner = `// Do not edit!
// This file is auto-generated by auto-export plugin (see vite.config.js)
`

// one generated module per source dir. pattern/replace mirror the autoExport(...) calls in
// vite.config.mjs exactly (dir is relative to src/).
const AUTO_EXPORTS = {
  "components-base": { dir: "common/components/base", pattern: /^bng([a-z\d]+)\.vue$/i, replace: "Bng$1" },
  "components-appsUtilities": { dir: "common/components/appsUtilities", pattern: /^bng([a-z\d]+)\.vue$/i, replace: "Bng$1" },
  "components-utility": { dir: "common/components/utility", pattern: /^([a-z])([a-z\d]+)\.vue$/i, replace: (_, n, ame) => n.toUpperCase() + ame },
  "components-directives": { dir: "common/directives", pattern: /^Bng([a-z\d]+)\.(?:js|vue)$/i, replace: "vBng$1" },
  "components-layouts": { dir: "common/layouts", pattern: /^([a-z])([a-z\d]+)\.vue$/i, replace: (_, n, ame) => n.toUpperCase() + ame },
}

// services nested under here are excluded from the mod-compiler importer map (matches vite config)
const MOD_EXCLUDED = [SRC_PATH + "services/modManager"]

const isExcluded = p => MOD_EXCLUDED.some(ex => p === ex || p.startsWith(ex + "/"))
const walkJs = prefix => filesUnder(prefix).filter(p => p.endsWith(".js"))

// auto-export module: re-export the default of every matching component file, plus a dev-only DEMOS
// map. Mirrors autoExport() in vite-auto-export.js, sourcing filenames from the lua index instead of fs.
function genAutoExport(name) {
  const { dir, pattern, replace } = AUTO_EXPORTS[name]
  const dirAbs = SRC_PATH + dir
  const outFile = name + ".js"
  const lines = [banner]
  const names = []

  for (const file of immediateFiles(dirAbs).sort()) {
    let n = file
    if (n === outFile) continue
    if (n.includes(".dev.")) {
      if (!RT_DEV) continue
      n = n.replace(".dev.", ".")
    }
    if (!pattern.test(n)) continue
    n = n.replace(pattern, replace)
    names.push(n)
    lines.push(`export { default as ${n} } from "${dirAbs}/${file}"`)
  }

  // demos are dev-only (the build gates them behind import.meta.hot)
  lines.push("", "export const DEMOS = " + (RT_DEV ? "{" : "{}"))
  if (RT_DEV) {
    const demosAbs = dirAbs + "/demos"
    for (const file of immediateFiles(demosAbs).sort()) {
      if (!file.endsWith(".vue")) continue // demos are always .vue
      if (!file.includes("_demo.")) continue
      let n = file.replace("_demo.", ".")
      if (!pattern.test(n)) continue
      n = n.replace(pattern, replace)
      if (!names.includes(n)) {
        console.warn(`[runtime-sfc] found demo for non-existent component ${n}`)
        continue
      }
      lines.push(`  ${n}: import("${demosAbs}/${file}"),`)
    }
    lines.push("}")
  }
  lines.push("")
  return lines.join("\n")
}

// mod compiler importer map: a name -> () => Promise(namespace) entry for the bridge index, every
// service (minus modManager), every util, and every index-mod.js barrel. Mirrors modCompilerImports().
function genModCompilerImports() {
  const bridgeIndex = SRC_PATH + "bridge/index.js"
  const servicesDir = SRC_PATH + "services"
  const utilsDir = SRC_PATH + "utils"

  const modules = []
  modules.push(bridgeIndex)
  modules.push(...walkJs(servicesDir).filter(p => !isExcluded(p)))
  modules.push(...walkJs(utilsDir))
  modules.push(...filesUnder(SRC_PATH).filter(p => p.endsWith("/index-mod.js")))

  const unique = [...new Set(modules)].sort((a, b) => a.localeCompare(b))

  const imports = []
  const mapEntries = []
  unique.forEach((p, i) => {
    const id = `mdl${i}`
    imports.push(`import * as ${id} from "${p}"`)
    const rel = p.slice(SRC_PATH.length) // e.g. "services/foo.js"
    for (const key of [`@/${rel}`, `/src/${rel}`]) {
      mapEntries.push(`  "${key}": () => Promise.resolve(${id}),`)
    }
  })

  return [banner, ...imports, "", "export const bundledImporters = {", ...mapEntries, "}", ""].join("\n")
}

// returns the synthesised ESM source for a /generated/* id, or null if it isn't one we generate
export function generatedSource(id) {
  if (!id.startsWith(GENERATED_PATH)) return null
  const name = id.slice(GENERATED_PATH.length).replace(/\.js$/, "")
  if (name === "mod-compiler-imports") return genModCompilerImports()
  if (Object.prototype.hasOwnProperty.call(AUTO_EXPORTS, name)) return genAutoExport(name)
  return null
}
