/**
 * Loading-screen hints. `includedInSimpleMenu` defaults to true when omitted.
 * Set `includedInSimpleMenu: false` to omit a hint while SimpleMenu is active.
 */
const ACTION_LABELS = {
  couplersToggle: "ui.inputActions.gameplay.couplersToggle.title",
  faster_motion: "ui.inputActions.slowmotion.faster_motion.title",
  loadHome: "ui.inputActions.gameplay.loadHome.title",
  menu_item_down: "ui.inputActions.controllerui.focus_d.title",
  menu_item_left: "ui.inputActions.controllerui.focus_l.title",
  menu_item_right: "ui.inputActions.controllerui.focus_r.title",
  menu_item_select: "ui.inputActions.controllerui.ok.title",
  menu_item_up: "ui.inputActions.controllerui.focus_u.title",
  movefast: "ui.inputActions.camera.movefast.title",
  nodegrabberRender: "ui.inputActions.gameplay.nodegrabberRender.title",
  parkingbrake: "ui.inputActions.vehicle.parkingbrake.title",
  parts_selector: "ui.inputActions.menu.parts_selector.title",
  publishScreenShot: "ui.inputActions.general.publishScreenShot.title",
  recover_vehicle: "ui.inputActions.gameplay.recover_vehicle.title",
  saveHome: "ui.inputActions.gameplay.saveHome.title",
  steer_left: "ui.inputActions.vehicle.steer_left.title",
  steer_right: "ui.inputActions.vehicle.steer_right.title",
  switch_next_vehicle: "ui.inputActions.gameplay.switch_next_vehicle.title",
  switch_previous_vehicle: "ui.inputActions.gameplay.switch_previous_vehicle.title",
  toggle_foglights: "ui.inputActions.vehicle.toggle_foglights.title",
  toggle_left_signal: "ui.inputActions.vehicle.toggle_left_signal.title",
  toggle_lightbar_signal: "ui.inputActions.vehicle.toggle_lightbar_signal.title",
  toggle_right_signal: "ui.inputActions.vehicle.toggle_right_signal.title",
  toggle_slow_motion: "ui.inputActions.slowmotion.toggle_slow_motion.title",
  toggleESCMode: "ui.inputActions.vehicle.toggleESCMode.title",
  toggleUi: "ui.inputActions.general.toggleUi.title",
  toggleWalkingMode: "ui.inputActions.gameplay.toggleWalkingMode.title",
  vehicle_selector: "ui.inputActions.menu.vehicle_selector.title",
}

const actionItem = action => ({ action, label: ACTION_LABELS[action] })

const HINT_ENTRIES = [
  { id: "ui.hints.quickSteerResponse", includedInSimpleMenu: false, actionItems: [actionItem("steer_left"), actionItem("steer_right")] },
  { id: "ui.hints.raceBrakesEffectiveness" },
  { id: "ui.hints.quickCameraMovement", includedInSimpleMenu: false, actionItems: [actionItem("movefast")] },
  { id: "ui.hints.grabVehicleParts", includedInSimpleMenu: false, actionItems: [actionItem("nodegrabberRender")] },
  { id: "ui.hints.funStabilityControl", includedInSimpleMenu: false, actionItems: [actionItem("toggleESCMode")] },
  { id: "ui.hints.recoverVehicle", actionItems: [actionItem("recover_vehicle")] },
  { id: "ui.hints.oldCarsBurn" },
  { id: "ui.hints.smokingWheels" },
  { id: "ui.hints.carsBurnFuel" },
  { id: "ui.hints.delicateCars" },
  { id: "ui.hints.stabilityControlPresent", includedInSimpleMenu: false },
  { id: "ui.hints.absWasOptional" },
  { id: "ui.hints.installRollCage", actionItems: [actionItem("parts_selector")] },
  { id: "ui.hints.spatialNavigation", includedInSimpleMenu: false, actionItems: [actionItem("menu_item_left"), actionItem("menu_item_up"), actionItem("menu_item_right"), actionItem("menu_item_down"), actionItem("menu_item_select")] },
  { id: "ui.hints.repairHood", actionItems: [actionItem("toggleWalkingMode")] },
  { id: "ui.hints.slowMotionPhysics", actionItems: [actionItem("toggle_slow_motion"), actionItem("faster_motion")] },
  { id: "ui.hints.removeRearSeats", includedInSimpleMenu: false, actionItems: [actionItem("parts_selector")] },
  { id: "ui.hints.tuning", includedInSimpleMenu: false, actionItems: [actionItem("parts_selector")] },
  { id: "ui.hints.customLicensePlate", includedInSimpleMenu: false, actionItems: [actionItem("parts_selector")] },
  { id: "ui.hints.driveAtNight" },
  { id: "ui.hints.moonGravity" },
  { id: "ui.hints.playMultiseat" },
  { id: "ui.hints.increaseGroundClearance" },
  { id: "ui.hints.tiresBurstOnBumps" },
  { id: "ui.hints.blueSmokeIsPistonDamage" },
  { id: "ui.hints.keepTheEngineUpright" },
  { id: "ui.hints.thermalDebugApp", includedInSimpleMenu: false },
  { id: "ui.hints.rollPitchApps", includedInSimpleMenu: false },
  { id: "ui.hints.cruiseControlApp", includedInSimpleMenu: false },
  { id: "ui.hints.driveTheCanon", includedInSimpleMenu: false, actionItems: [actionItem("vehicle_selector")] },
  { id: "ui.hints.vehicleSkins", includedInSimpleMenu: false, actionItems: [actionItem("parts_selector")] },
  { id: "ui.hints.toggleMods", includedInSimpleMenu: false },
  { id: "ui.hints.importveFramerate", includedInSimpleMenu: false },
  { id: "ui.hints.photoModeMenu", includedInSimpleMenu: false },
  { id: "ui.hints.publishScreenshots", includedInSimpleMenu: false, actionItems: [actionItem("toggleUi"), actionItem("publishScreenShot")] },
  { id: "ui.hints.towTrailer", includedInSimpleMenu: false, actionItems: [actionItem("vehicle_selector"), actionItem("couplersToggle")] },
  { id: "ui.hints.brakesAndSteeringVary" },
  { id: "ui.hints.countersteerEarly", includedInSimpleMenu: false },
  { id: "ui.hints.startSlow" },
  { id: "ui.hints.parkingbrakeForTurning", actionItems: [actionItem("parkingbrake")] },
  { id: "ui.hints.carefulWithOldSportsCars" },
  { id: "ui.hints.corneringWithKeyboard", includedInSimpleMenu: false, actionItems: [actionItem("steer_left"), actionItem("steer_right")] },
  { id: "ui.hints.adaptToBadRoads" },
  { id: "ui.hints.notAllCarsCanRace", includedInSimpleMenu: false, actionItems: [actionItem("parts_selector")] },
  { id: "ui.hints.changeBrakePads", includedInSimpleMenu: false, actionItems: [actionItem("parts_selector")] },
  { id: "ui.hints.useTurnSignals", includedInSimpleMenu: false, actionItems: [actionItem("toggle_left_signal"), actionItem("toggle_right_signal")] },
  { id: "ui.hints.showStandalonePcs" },
  { id: "ui.hints.tweakFOV", includedInSimpleMenu: false },
  { id: "ui.hints.driveWithMouse", includedInSimpleMenu: false },
  { id: "ui.hints.liftOffOversteer" },
  { id: "ui.hints.snapOversteer" },
  { id: "ui.hints.slideBackWithParkingBrake" },
  { id: "ui.hints.toggleFogLights", includedInSimpleMenu: false, actionItems: [actionItem("toggle_foglights")] },
  { id: "ui.hints.toggleLightBars", includedInSimpleMenu: false, actionItems: [actionItem("toggle_lightbar_signal")] },
  { id: "ui.hints.TrackIRSupported", includedInSimpleMenu: false },
  { id: "ui.hints.chooseShiftingMode" },
  { id: "ui.hints.saveRestoreVehicleHome", includedInSimpleMenu: false, actionItems: [actionItem("saveHome"), actionItem("loadHome")] },
  { id: "ui.hints.switchVehicle", includedInSimpleMenu: false, actionItems: [actionItem("switch_next_vehicle"), actionItem("switch_previous_vehicle")] },
  { id: "ui.hints.coolantVaporizes", actionItems: [actionItem("recover_vehicle")] },
  { id: "ui.hints.dontRunIntoTheCar" },
]

const allHints = HINT_ENTRIES.map(e => ({ ...e }))

export function getHints(simplemenuActive) {
  if (!simplemenuActive) return [...allHints]
  const filtered = HINT_ENTRIES.filter(e => e.includedInSimpleMenu !== false).map(e => ({ ...e }))
  return filtered.length ? filtered : [...allHints]
}
